from pipeline.models import Country, Currency, Sector

# Canonical country names plus known source-specific aliases (e.g. STOXX uses "Great Britain")
COUNTRY_MAP: dict[str, Country] = {
    "Australia":      Country.AUSTRALIA,
    "Austria":        Country.AUSTRIA,
    "Belgium":        Country.BELGIUM,
    "Brazil":         Country.BRAZIL,
    "Canada":         Country.CANADA,
    "Chile":          Country.CHILE,
    "China":          Country.CHINA,
    "Colombia":       Country.COLOMBIA,
    "Cyprus":         Country.CYPRUS,
    "Czech Republic": Country.CZECH_REPUBLIC,
    "Denmark":        Country.DENMARK,
    "Egypt":          Country.EGYPT,
    "Finland":        Country.FINLAND,
    "France":         Country.FRANCE,
    "Germany":        Country.GERMANY,
    "Great Britain":  Country.UNITED_KINGDOM,
    "Greece":         Country.GREECE,
    "Hong Kong":      Country.HONG_KONG,
    "Hungary":        Country.HUNGARY,
    "India":          Country.INDIA,
    "Indonesia":      Country.INDONESIA,
    "Ireland":        Country.IRELAND,
    "Israel":         Country.ISRAEL,
    "Italy":          Country.ITALY,
    "Japan":          Country.JAPAN,
    "Kuwait":         Country.KUWAIT,
    "Luxembourg":     Country.LUXEMBOURG,
    "Malaysia":       Country.MALAYSIA,
    "Mexico":         Country.MEXICO,
    "Netherlands":    Country.NETHERLANDS,
    "New Zealand":    Country.NEW_ZEALAND,
    "Norway":         Country.NORWAY,
    "Peru":           Country.PERU,
    "Philippines":    Country.PHILIPPINES,
    "Poland":         Country.POLAND,
    "Portugal":       Country.PORTUGAL,
    "Qatar":          Country.QATAR,
    "Russia":         Country.RUSSIA,
    "Saudi Arabia":   Country.SAUDI_ARABIA,
    "Singapore":      Country.SINGAPORE,
    "South Africa":   Country.SOUTH_AFRICA,
    "South Korea":    Country.SOUTH_KOREA,
    "Spain":          Country.SPAIN,
    "Sweden":         Country.SWEDEN,
    "Switzerland":    Country.SWITZERLAND,
    "Taiwan":         Country.TAIWAN,
    "Thailand":       Country.THAILAND,
    "Turkey":         Country.TURKEY,
    "United Arab Emirates": Country.UNITED_ARAB_EMIRATES,
    "United Kingdom": Country.UNITED_KINGDOM,
    "United States":  Country.UNITED_STATES,
    
    # DWS Italian aliases
    "Belgio":                                  Country.BELGIUM,
    "Brasile":                                 Country.BRAZIL,
    "Cile":                                    Country.CHILE,
    "Cina":                                    Country.CHINA,
    "Danimarca":                               Country.DENMARK,
    "Finlandia":                               Country.FINLAND,
    "Francia":                                 Country.FRANCE,
    "Germania":                                Country.GERMANY,
    "Giappone":                                Country.JAPAN,
    "Irlanda":                                 Country.IRELAND,
    "Israele":                                 Country.ISRAEL,
    "Italia":                                  Country.ITALY,
    "Jersey":                                  Country.JERSEY,
    "Lussemburgo":                             Country.LUXEMBOURG,
    "Macao":                                   Country.MACAU,
    "Norvegia":                                Country.NORWAY,
    "Nuova Zelanda":                           Country.NEW_ZEALAND,
    "Paesi Bassi (Olanda)":                    Country.NETHERLANDS,
    "Polonia":                                 Country.POLAND,
    "Portogallo":                              Country.PORTUGAL,
    "Regno Unito":                             Country.UNITED_KINGDOM,
    "Repubblica Ceca":                         Country.CZECH_REPUBLIC,
    "Repubblica di Corea (Corea del Sud)":     Country.SOUTH_KOREA,
    "Spagna":                                  Country.SPAIN,
    "Stati Uniti d'America":                   Country.UNITED_STATES,
    "Svezia":                                  Country.SWEDEN,
    "Svizzera":                                Country.SWITZERLAND,
    "Zambia":                                  Country.ZAMBIA,
}

CURRENCY_MAP: dict[Country, Currency] = {
    Country.AUSTRALIA:           Currency.AUD,
    Country.AUSTRIA:             Currency.EUR,
    Country.BELGIUM:             Currency.EUR,
    Country.BRAZIL:              Currency.BRL,
    Country.CANADA:              Currency.CAD,
    Country.CHILE:               Currency.CLP,
    Country.CHINA:               Currency.CNY,
    Country.COLOMBIA:            Currency.COP,
    Country.CYPRUS:              Currency.EUR,
    Country.CZECH_REPUBLIC:      Currency.CZK,
    Country.DENMARK:             Currency.DKK,
    Country.EGYPT:               Currency.EGP,
    Country.FINLAND:             Currency.EUR,
    Country.FRANCE:              Currency.EUR,
    Country.GERMANY:             Currency.EUR,
    Country.GREECE:              Currency.EUR,
    Country.HONG_KONG:           Currency.HKD,
    Country.HUNGARY:             Currency.HUF,
    Country.INDIA:               Currency.INR,
    Country.INDONESIA:           Currency.IDR,
    Country.IRELAND:             Currency.EUR,
    Country.ISRAEL:              Currency.ILS,
    Country.ITALY:               Currency.EUR,
    Country.JAPAN:               Currency.JPY,
    Country.JERSEY:              Currency.GBP,
    Country.KUWAIT:              Currency.KWD,
    Country.LUXEMBOURG:          Currency.EUR,
    Country.MACAU:               Currency.MOP,
    Country.MALAYSIA:            Currency.MYR,
    Country.MEXICO:              Currency.MXN,
    Country.NETHERLANDS:         Currency.EUR,
    Country.NEW_ZEALAND:         Currency.NZD,
    Country.NORWAY:              Currency.NOK,
    Country.PERU:                Currency.PEN,
    Country.PHILIPPINES:         Currency.PHP,
    Country.POLAND:              Currency.PLN,
    Country.PORTUGAL:            Currency.EUR,
    Country.QATAR:               Currency.QAR,
    Country.RUSSIA:              Currency.RUB,
    Country.SAUDI_ARABIA:        Currency.SAR,
    Country.SINGAPORE:           Currency.SGD,
    Country.SOUTH_AFRICA:        Currency.ZAR,
    Country.SOUTH_KOREA:         Currency.KRW,
    Country.SPAIN:               Currency.EUR,
    Country.SWEDEN:              Currency.SEK,
    Country.SWITZERLAND:         Currency.CHF,
    Country.TAIWAN:              Currency.TWD,
    Country.THAILAND:            Currency.THB,
    Country.TURKEY:              Currency.TRY,
    Country.UNITED_ARAB_EMIRATES: Currency.AED,
    Country.UNITED_KINGDOM:      Currency.GBP,
    Country.UNITED_STATES:       Currency.USD,
    Country.ZAMBIA:              Currency.ZMW,
}

# GICS sector names (canonical) plus STOXX supersector aliases
SECTOR_MAP: dict[str, Sector] = {
    # GICS canonical names
    "Communication Services": Sector.COMMUNICATION_SERVICES,
    "Consumer Discretionary": Sector.CONSUMER_DISCRETIONARY,
    "Consumer Staples":       Sector.CONSUMER_STAPLES,
    "Energy":                 Sector.ENERGY,
    "Financials":             Sector.FINANCIALS,
    "Health Care":            Sector.HEALTH_CARE,
    "Industrials":            Sector.INDUSTRIALS,
    "Information Technology": Sector.INFORMATION_TECHNOLOGY,
    "Materials":              Sector.MATERIALS,
    "Real Estate":            Sector.REAL_ESTATE,
    "Utilities":              Sector.UTILITIES,
    # STOXX supersector aliases
    "Automobiles & Parts":                  Sector.CONSUMER_DISCRETIONARY,
    "Banks":                                Sector.FINANCIALS,
    "Basic Resources":                      Sector.MATERIALS,
    "Chemicals":                            Sector.MATERIALS,
    "Construction & Materials":             Sector.INDUSTRIALS,
    "Consumer Products & Services":         Sector.CONSUMER_DISCRETIONARY,
    "Financial Services":                   Sector.FINANCIALS,
    "Food, Beverage & Tobacco":             Sector.CONSUMER_STAPLES,
    "Industrial Goods & Services":          Sector.INDUSTRIALS,
    "Insurance":                            Sector.FINANCIALS,
    "Media":                                Sector.COMMUNICATION_SERVICES,
    "Personal Care, Drug & Grocery Stores": Sector.CONSUMER_STAPLES,
    "Retail":                               Sector.CONSUMER_DISCRETIONARY,
    "Technology":                           Sector.INFORMATION_TECHNOLOGY,
    "Telecommunications":                   Sector.COMMUNICATION_SERVICES,
    "Travel & Leisure":                     Sector.CONSUMER_DISCRETIONARY,
    # Ishares sector aliases
    "Communication":                       Sector.COMMUNICATION_SERVICES,
    "Unassigned":                          Sector.UNKNOWN,
    # DWS Italian sector aliases
    "Beni di prima necessità":             Sector.CONSUMER_STAPLES,
    "Beni voluttuari":                     Sector.CONSUMER_DISCRETIONARY,
    "Energia":                             Sector.ENERGY,
    "Finanza":                             Sector.FINANCIALS,
    "Immobiliare":                         Sector.REAL_ESTATE,
    "Materiali":                           Sector.MATERIALS,
    "Prodotti industriali":                Sector.INDUSTRIALS,
    "Sanità":                              Sector.HEALTH_CARE,
    "Servizi di comunicazione":            Sector.COMMUNICATION_SERVICES,
    "Servizi di pubblica utilità":         Sector.UTILITIES,
    "Tecnologia dell'informazione":        Sector.INFORMATION_TECHNOLOGY,
    "sconosciuta":                         Sector.UNKNOWN,
}


def resolve_country(raw: str) -> Country:
    result = COUNTRY_MAP.get(raw)
    if result is None:
        raise ValueError(f"Unknown country '{raw}'")
    return result


def resolve_currency(country: Country) -> Currency:
    result = CURRENCY_MAP.get(country)
    if result is None:
        raise ValueError(f"No currency mapping for country '{country.value}'")
    return result


def resolve_sector(raw: str) -> Sector:
    result = SECTOR_MAP.get(raw)
    if result is None:
        raise ValueError(f"Unknown sector '{raw}'")
    return result
