from dataclasses import dataclass
from enum import Enum


class Currency(str, Enum):
    AED = "AED"
    AUD = "AUD"
    BRL = "BRL"
    CAD = "CAD"
    CHF = "CHF"
    CLP = "CLP"
    CNY = "CNY"
    COP = "COP"
    CZK = "CZK"
    DKK = "DKK"
    EGP = "EGP"
    EUR = "EUR"
    GBP = "GBP"
    HKD = "HKD"
    HUF = "HUF"
    IDR = "IDR"
    ILS = "ILS"
    INR = "INR"
    JPY = "JPY"
    KRW = "KRW"
    KWD = "KWD"
    MOP = "MOP"
    MXN = "MXN"
    MYR = "MYR"
    NOK = "NOK"
    NZD = "NZD"
    PEN = "PEN"
    PHP = "PHP"
    PLN = "PLN"
    QAR = "QAR"
    RUB = "RUB"
    SAR = "SAR"
    SEK = "SEK"
    SGD = "SGD"
    THB = "THB"
    TRY = "TRY"
    TWD = "TWD"
    UAH = "UAH"
    USD = "USD"
    ZAR = "ZAR"
    ZMW = "ZMW"


class Country(str, Enum):
    AUSTRALIA      = "Australia"
    AUSTRIA        = "Austria"
    BELGIUM        = "Belgium"
    BRAZIL         = "Brazil"
    CANADA         = "Canada"
    CHILE          = "Chile"
    CHINA          = "China"
    COLOMBIA       = "Colombia"
    CYPRUS         = "Cyprus"
    CZECH_REPUBLIC = "Czech Republic"
    DENMARK        = "Denmark"
    EGYPT          = "Egypt"
    FINLAND        = "Finland"
    FRANCE         = "France"
    GERMANY        = "Germany"
    GREECE         = "Greece"
    HONG_KONG      = "Hong Kong"
    HUNGARY        = "Hungary"
    INDIA          = "India"
    INDONESIA      = "Indonesia"
    IRELAND        = "Ireland"
    ISLE_OF_MAN    = "Isle of Man"
    ISRAEL         = "Israel"
    ITALY          = "Italy"
    JAPAN          = "Japan"
    JERSEY         = "Jersey"
    KUWAIT         = "Kuwait"
    LUXEMBOURG     = "Luxembourg"
    MACAU          = "Macau"
    MALAYSIA       = "Malaysia"
    MEXICO         = "Mexico"
    NETHERLANDS    = "Netherlands"
    NEW_ZEALAND    = "New Zealand"
    NORWAY         = "Norway"
    PERU           = "Peru"
    PHILIPPINES    = "Philippines"
    POLAND         = "Poland"
    PORTUGAL       = "Portugal"
    QATAR          = "Qatar"
    RUSSIA         = "Russia"
    SAUDI_ARABIA   = "Saudi Arabia"
    SINGAPORE      = "Singapore"
    SOUTH_AFRICA   = "South Africa"
    SOUTH_KOREA    = "South Korea"
    SPAIN          = "Spain"
    SWEDEN         = "Sweden"
    SWITZERLAND    = "Switzerland"
    TAIWAN         = "Taiwan"
    THAILAND       = "Thailand"
    TURKEY         = "Turkey"
    UKRAINE        = "Ukraine"
    UNITED_ARAB_EMIRATES = "United Arab Emirates"
    UNITED_KINGDOM = "United Kingdom"
    UNITED_STATES  = "United States"
    ZAMBIA         = "Zambia"


class Sector(str, Enum):
    # GICS sectors — used as the canonical taxonomy across all indices
    COMMUNICATION_SERVICES = "Communication Services"
    CONSUMER_DISCRETIONARY = "Consumer Discretionary"
    CONSUMER_STAPLES       = "Consumer Staples"
    ENERGY                 = "Energy"
    FINANCIALS             = "Financials"
    HEALTH_CARE            = "Health Care"
    INDUSTRIALS            = "Industrials"
    INFORMATION_TECHNOLOGY = "Information Technology"
    MATERIALS              = "Materials"
    REAL_ESTATE            = "Real Estate"
    UTILITIES              = "Utilities"
    UNKNOWN                = "Unknown"


@dataclass
class Holding:
    name: str
    country: Country
    currency: Currency
    sector: Sector
    weight: float          # 0.0–1.0
    isin: str | None = None
